---

  - name: create/destroy master
    os_server:
      state: "{{ instance_state }}"
      name: "{{ cluster_name }}-master"
      image: "{{ os_image }}"
      flavor: "{{ master_flavor }}"
      key_name: "{{ os_key_name }}"
      floating_ip_pools: "{{ floating_ip_pool }}"
      network: "{{ virtual_network }}"
      boot_from_volume: "{{ boot_from_volume }}"
      #security_groups: "{{ cluster_name }}-master"
      meta: "hostname={{ cluster_name }}-master,group={{ cluster_name }}_master"
    retries: 3
#    async: 300
#    poll: 0
#    register: master_waitress

  - name: create/destroy slaves
    os_server:
      state: "{{ instance_state }}"
      name: "{{ item }}"
      image: "{{ os_image }}"
      flavor: "{{ flavor }}"
      key_name: "{{ os_key_name }}"
      floating_ip_pools: "{{ floating_ip_pool }}"
      network: "{{ virtual_network }}"
      boot_from_volume: "{{ boot_from_volume }}"
      #security_groups: "{{ cluster_name }}-slaves"
      meta: "hostname={{ item }},group={{ cluster_name }}_slaves"
    with_sequence: start=1 end={{ n_slaves }} format={{ cluster_name }}-slave-%d
    retries: 3

#   Async instances creation: it works but Openstack can not handle >10 simultinous queries
#    async: 1000
#    poll: 0
#    register: slave_waitress
#
#  - name: 'Checking master started or dead'
#    async_status: jid={{ master_waitress.ansible_job_id }}
#    register: mstr
#    until: mstr.finished
#    retries: 30
#
#  - name: 'Checking slaves started or dead'
#    async_status: jid={{ item.ansible_job_id }}
#    register: slv
#    until: slv.finished
#    retries: 120
#    with_items: "{{ slave_waitress.results }}"

