cluster_manager_addresses: >-
  {{ groups.spark_managers | map('extract', hostvars, 'ansible_host') }}
primary_cluster_manager: >-
  {{ groups.spark_managers.0 }}
primary_cluster_manager_address: >-
  {{ hostvars[primary_cluster_manager].ansible_host }}

cluster_worker_addresses: >-
  {{ groups.spark_workers | map('extract', hostvars, 'ansible_host') }}
worker_count: >-
  {{ groups.spark_workers | length }}

reserved_memory_mb: >-
  {% if ansible_facts.memtotal_mb < 512 * 3 %}
  {{ 512 }}
  {% elif ansible_facts.memtotal_mb < 1024 * 8 %}
  {{ 1280 }}
  {% elif ansible_facts.memtotal_mb < 1024 * 10 %}
  {{
    (ansible_facts.memtotal_mb // 256) * 0.15
    | round(0, 'floor')
    * 256
  }}
  {% elif ansible_facts.memtotal_mb < 1024 * 100 %}
  {{
    (ansible_facts.memtotal_mb // 1024) * 0.15
    | round(0, 'floor')
    * 1024
  }}
  {% else %}
  {{ 1024 * 15 }}
  {% endif %}

spark_worker_memory_mb: >-
  {{ ansible_facts.memtotal_mb - reserved_memory_mb | int }}

spark_worker_cores: >-
  {{ ansible_facts.processor_nproc }}
