cluster_manager_addresses: >-
  {{ groups.spark_managers | map('extract', hostvars, 'ansible_host') }}
primary_cluster_manager: >-
  {{ groups.spark_managers.0 }}
primary_cluster_manager_address: >-
  {{ hostvars[primary_cluster_manager].ansible_host }}

cluster_worker_addresses: >-
  {{ groups.spark_workers | map('extract', hostvars, 'ansible_host') }}
worker_count: >-
  {{ groups.spark_workers | length }}

# https://spark.apache.org/docs/latest/hardware-provisioning.html
worker_reserved_memory_ratio: 0.25

worker_reserved_memory_mb: >-
  {% if ansible_facts.memtotal_mb < 512 * 4 %}
  {{ 512 }}
  {% else %}
  {{ ansible_facts.memtotal_mb * worker_reserved_memory_ratio }}
  {% endif %}

spark_worker_memory_mb: >-
  {{ ansible_facts.memtotal_mb - worker_reserved_memory_mb | int }}

spark_worker_cores: >-
  {{ ansible_facts.processor_nproc }}
