---

- name: update apt cache
  apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - nfs-kernel-server
    - nfs-common

- name: create dir
  file: path={{nfs_share_mnt}} state=directory owner={{nfs_user}}

- name: crate mount point
  lineinfile:
    dest=/etc/fstab
    state=present insertafter=EOF
    line="{{ nfs_share_path }}  {{nfs_share_mnt}}       nfs    owner={{nfs_user}}        0       2"
    create=true

- name: mount
  shell: mount -a
