---

- name: update apt cache
  apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - nfs-kernel-server
    - nfs-common

- include: add_share.yml
  with_items: "{{nfs_shares}}"

- name: mount
  shell: mount -a
