---

- hosts: "{{ cluster_name }}_master"
  tasks:
    - command: /opt/spark/sbin/stop-slaves.sh
    - command: /opt/spark/sbin/stop-master.sh
    - command: /usr/local/hadoop/sbin/stop-dfs.sh

- hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  tasks:
    - command: killall -9 java
      ignore_errors: yes

- hosts: "{{ cluster_name }}_master"
  tasks:
    - command: /usr/local/hadoop/sbin/start-dfs.sh
    - command: /opt/spark/sbin/start-master.sh
    - command: /opt/spark/sbin/start-slaves.sh
