---

#FIXME: need full path to be included directly
- include_vars: "{{roles_dir|default('roles')}}/jupyter/vars/python{{ python_version }}.yml"

- block:
  - name: update apt cache
    apt: update_cache=yes

  - name: install packages
    package: name={{ item }} state=present
    with_items:
      - "{{apt_pkg_pref}}-dev"
      - "{{apt_pkg_pref}}-tk" #needed for pyspark
      - "{{apt_pkg_pref}}-scipy"
      - libfreetype6-dev
      - libpng12-dev
      - pkg-config
    register: result
    ignore_errors: True
    until: result|success
    retries: 3
    #TODO: failures are ignored

  - name: downlad get-pip.py
    get_url:
      url="https://bootstrap.pypa.io/get-pip.py"
      dest=/tmp/
  - name: install pip
    raw: "{{apt_pkg_pref}} /tmp/get-pip.py"

    #looks like pyparsing==2.1.2 does not work on python 3 (AttributeError: 'tuple' object has no attribute 'filename')
    #as a result of this matplotlib does not work either
  - name: install pyparsing
    pip: name=pyparsing version=2.1.1 state=present executable=pip{{ python_version }}
    when: python_version|int == 3

  - name: install pip packages
    pip: name={{ item }} state=present executable=pip{{ python_version }}
    with_items:
      - jupyter
      - numpy
      - pandas
      - matplotlib
      - scipy
      - seaborn
      - scikit-learn
    register: result
    ignore_errors: True
    until: result|success
    retries: 3
    #TODO: failures are ignored

  - name: install toree
    pip: name=toree state=present executable=pip{{ python_version }} extra_args="--pre"
  become: True
  become_user: root
