---

#FIXME: need full path to be included directly

- block:
  - name: Python package prefix
    debug: var=apt_pkg_pref

  - name: install packages
    package: name={{ item }} state=present
    with_items:
      # Core
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-wheel
      # Packages
      - python3-scipy
      - python3-tk # needed for pyspark
      # Deps
      - libfreetype6-dev
      - libpng-dev
      - pkg-config
    register: result
    ignore_errors: True
    until: result is success
    retries: 3
    # TODO: failures are ignored

  - name: install pip packages
    become: yes
    pip:
      name:
        - jupyter
        - matplotlib
        - numpy
        - pandas
        - pyparsing
        - scikit-learn
        - scipy
        - seaborn
        - "toree=={{ toree_version }}"
      state: present
      virtualenv: /opt/spark-openstack-venv/
      virtualenv_command: /usr/bin/python3 -m venv
    register: result
    ignore_errors: True
    until: result is success
    retries: 3

  become: True
  become_user: root
  tags:
  - install
  - jupyter_install
