---

#FIXME: need full path to be included directly
- include_vars: "{{roles_dir|default('roles')}}/jupyter/vars/python{{ python_version }}.yml"

- block:
  - name: update apt cache
    apt: update_cache=yes

  - name: install packages
    package: name={{ item }} state=present
    with_items:
      - "{{apt_pkg_pref}}-dev"
      - "{{apt_pkg_pref}}-tk" #needed for pyspark
      - "{{apt_pkg_pref}}-scipy"
      - libfreetype6-dev
      - libpng12-dev
      - pkg-config
    register: result
    ignore_errors: True
    until: result|success
    retries: 3
    #TODO: failures are ignored

  - name: downlad get-pip.py
    get_url:
      url="https://bootstrap.pypa.io/get-pip.py"
      dest=/tmp/
  - name: install pip
    raw: "{{apt_pkg_pref}} /tmp/get-pip.py"

    #looks like pyparsing==2.1.2 does not work on python 3 (AttributeError: 'tuple' object has no attribute 'filename')
    #as a result of this matplotlib does not work either
  - name: install pyparsing
    pip: name=pyparsing version=2.1.1 state=present executable=pip{{ python_version }}
    when: python_version|int == 3

  - name: install pip packages
    pip: name={{ item }} state=present executable=pip{{ python_version }}
    with_items:
      - jupyter
      - numpy
      - pandas
      - matplotlib
      - scipy
      - seaborn
      - scikit-learn
    register: result
    ignore_errors: True
    until: result|success
    retries: 3
    #TODO: failures are ignored

    #TODO: add 'pip install pyOpenSSL ndg-httpsclient pyasn1' to fix SNIMissingWarning in old python versions
    #      (see http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package)

  #FIXME for Spark version >= 2.0, should use newer versions of toree
  #  e.g. https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0/snapshots/dev1/toree-pip/toree-0.2.0.dev1.tar.gz
  - name: install toree
    pip: name="https://dist.apache.org/repos/dist/dev/incubator/toree/0.1.0/rc6/toree-pip/apache-toree-0.1.0.tar.gz" state=present executable=pip{{ python_version }}
  become: True
  become_user: root
