---

- block:
  - include: tasks/prepare_ubuntu.yml

  - include: as_root.yml
    become: yes
    become_user: root
  when: spark_common_completed is undefined

- set_fact:
    spark_common_completed: true

